MNIST Handwritten Digit recognition as a regression problem using DNN

CJ Nov 2023

In [11]:
from keras import layers, models
from keras.datasets import mnist
from sklearn.model_selection import train_test_split

In [12]:
# Load and preprocess the MNIST dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.1, random_state=42)

# Normalize pixel values to be between 0 and 1
x_train, x_val, x_test = x_train / 255.0, x_val / 255.0, x_test / 255.0

# Flatten the images. Q: Do we need to flatten???

x_train = x_train.reshape((x_train.shape[0], -1))
x_val = x_val.reshape((x_val.shape[0], -1))
x_test2 = x_test.reshape((x_test.shape[0], -1)) # x_test is saved for display

In [13]:
# Define the model
model = models.Sequential([
    layers.Dense(512, activation='relu', input_shape=(784,)), # DNN needs flattened
    layers.Dense(128, activation='relu'),
    layers.Dense(32, activation='relu'),
    layers.Dense(1)  # One output neuron for regression
])

In [14]:
# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])

# Train the model
model.fit(x_train, y_train, epochs=20, batch_size=32, validation_data=(x_val, y_val))



Epoch 1/20
1688/1688 [==============================] - 14s 8ms/step - loss: 1.3504 - mae: 0.7517 - val_loss: 0.9446 - val_mae: 0.6215
Epoch 2/20
1688/1688 [==============================] - 13s 8ms/step - loss: 0.5950 - mae: 0.4556 - val_loss: 0.6445 - val_mae: 0.4486
Epoch 3/20
1688/1688 [==============================] - 14s 9ms/step - loss: 0.4018 - mae: 0.3542 - val_loss: 0.5357 - val_mae: 0.3697
Epoch 4/20
1688/1688 [==============================] - 13s 8ms/step - loss: 0.3093 - mae: 0.2981 - val_loss: 0.4224 - val_mae: 0.3203
Epoch 5/20
1688/1688 [==============================] - 13s 8ms/step - loss: 0.2464 - mae: 0.2595 - val_loss: 0.3919 - val_mae: 0.3058
Epoch 6/20
1688/1688 [==============================] - 13s 8ms/step - loss: 0.2083 - mae: 0.2346 - val_loss: 0.3731 - val_mae: 0.2651
Epoch 7/20
1688/1688 [==============================] - 13s 8ms/step - loss: 0.1699 - mae: 0.2067 - val_loss: 0.4298 - val_mae: 0.2844
Epoch 8/20
1688/1688 [==============================] -

In [15]:
# Evaluate the model on the test set
test_loss, test_mae = model.evaluate(x_test2, y_test)
print(f'Test Mean Squared Error: {test_loss}, Test Mean Absolute Error: {test_mae}')

313/313 [==============================] - 1s 2ms/step - loss: 0.2872 - mae: 0.1493
Test Mean Squared Error: 0.28721147775650024, Test Mean Absolute Error: 0.1493115872144699


In [16]:
print(y_test)

[7 2 1 ... 4 5 6]


In [40]:
print(x_test2[0:3].shape)
print(x_test2[1].shape)
print(x_test2[-1].shape)

(3, 784)
(784,)
(784,)


In [38]:
import numpy as np
print(model.predict( x_test2[0:3] ))


1/1 [==============================] - 0s 21ms/step
[[6.9679785]
 [1.9699008]
 [1.0470324]]


In [44]:
print(model.predict(np.array([x_test2[1 ]])   ))
print(model.predict(np.array([x_test2[-1]])   )) # last item
print(model.predict(x_test2[-3:])) # last 3 items

1/1 [==============================] - 0s 49ms/step
[[1.9699008]]
1/1 [==============================] - 0s 33ms/step
[[5.9274044]]
1/1 [==============================] - 0s 30ms/step
[[3.9106052]
 [4.9736114]
 [5.9274044]]
