# Training & testing OR function using Keras
The simplest Keras NN code in the world by CJ!

In [1]:
from keras.models import Sequential
from keras.layers import Dense
from keras import optimizers
import numpy as np

# training data. Bias "1" is not needed in Keras
X = np.array([[0,0], [0,1], [1,0], [1,1]]) #training data
y = np.array([[0],   [1],   [1],   [1]  ]) #target labels
X1 = np.array([[0.1,0], [0,0.9], [0.9,0], [1,0.9]]) # Unseen & unlabeled data

In [2]:
model = Sequential([
    Dense(1, input_dim=2, activation="sigmoid")
])

model.compile(
    loss='mean_squared_error', # https://keras.io/losses/
    optimizer=optimizers.RMSprop(learning_rate=0.1), # https://keras.io/optimizers/
    metrics=["binary_accuracy"] # for binary classification problem
)

# batch_size: num of samples per weight update
# An epoch is an iteration over the entire X and y data provided
model.fit(X, y, batch_size=1, epochs=15)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - binary_accuracy: 0.7333 - loss: 0.1967
Epoch 2/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - binary_accuracy: 0.8333 - loss: 0.1289 
Epoch 3/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.7333 - loss: 0.1229 
Epoch 4/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.5333 - loss: 0.1823     
Epoch 5/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.7333 - loss: 0.1166 
Epoch 6/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.5333 - loss: 0.1683     
Epoch 7/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.9000 - loss: 0.0524 
Epoch 8/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.5333 - loss: 0.1414     
Epoch 9/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.7333 - loss: 0.0873 
Epoch 10/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.8333 - loss: 0.0673 
Epoch 11/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 1.0000 - loss: 0.0

In [3]:
# Test, Inference
print(model.predict(X))
print(model.predict(X1)) # Unseen dataset
print(model.predict(X1).round())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step
[[0.35469028]
 [0.91678923]
 [0.8299385 ]
 [0.98988116]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step
[[0.4060985]
 [0.8908743]
 [0.7968665]
 [0.9863917]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
[[0.]
 [1.]
 [1.]
 [1.]]


In [4]:
# print learned weight values
for layer in model.layers:
  print(layer.get_weights())

[array([[2.1836767],
       [2.9979868]], dtype=float32), array([-0.59848547], dtype=float32)]


In [5]:
print(model.predict( np.array([X[0]]), verbose=0 )) # to get a label of the first sample

[[0.35469028]]


In [6]:
print(model.predict( np.array([ [0.1, 0.05]]), verbose=0 )) # to get a lable of a test sample

[[0.44269827]]


In [7]:
# Evaluate the model with X1
loss, accuracy = model.evaluate(X1, y, verbose=0)
print(f"Loss on X1: {loss:.4f}")
print(f"Accuracy on X1: {accuracy:.4f}")

Loss on X1: 0.0546
Accuracy on X1: 1.0000


In [8]:
import numpy as np

def sigmoid(x):
  return 1 / (1 + np.exp(-x))

# Example usage
print(sigmoid(0.01))


0.502499979166875
