## Simple Time Series - Univariate time series forecasting and make a single prediction

"univariate time series" refers to a time series that consists of single (scalar) observations recorded sequentially over equal time increments.

In [1]:
# univariate LSTM, SimpleRNN example
from numpy import array # instead of using np.array

# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
	X = []
	y = []
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

# define input sequence
# for HW7
# raw_seq = [0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55,
#           0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95]

raw_seq = [0., .1, .2, .3, .4, .5, .6, .7, .8, .9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5]
# choose a number of time steps
n_steps = 3

# split into samples
X0, y = split_sequence(raw_seq, n_steps)
print(X0)
print(y)

[[0.  0.1 0.2]
 [0.1 0.2 0.3]
 [0.2 0.3 0.4]
 [0.3 0.4 0.5]
 [0.4 0.5 0.6]
 [0.5 0.6 0.7]
 [0.6 0.7 0.8]
 [0.7 0.8 0.9]
 [0.8 0.9 1. ]
 [0.9 1.  1.1]
 [1.  1.1 1.2]
 [1.1 1.2 1.3]
 [1.2 1.3 1.4]]
[0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5]


In [2]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X0.reshape((X0.shape[0], X0.shape[1], n_features))
print(X.shape)
print(X)

(13, 3, 1)
[[[0. ]
  [0.1]
  [0.2]]

 [[0.1]
  [0.2]
  [0.3]]

 [[0.2]
  [0.3]
  [0.4]]

 [[0.3]
  [0.4]
  [0.5]]

 [[0.4]
  [0.5]
  [0.6]]

 [[0.5]
  [0.6]
  [0.7]]

 [[0.6]
  [0.7]
  [0.8]]

 [[0.7]
  [0.8]
  [0.9]]

 [[0.8]
  [0.9]
  [1. ]]

 [[0.9]
  [1. ]
  [1.1]]

 [[1. ]
  [1.1]
  [1.2]]

 [[1.1]
  [1.2]
  [1.3]]

 [[1.2]
  [1.3]
  [1.4]]]


#### DENSE Network

In [3]:
import keras
from keras import layers
model3 = keras.Sequential([
    #layers.Dense(16, activation='sigmoid', input_shape=(n_steps,)),
    layers.Dense(16, activation='sigmoid'),
    layers.Dense(8, activation='relu'),
    layers.Dense(1)
])

model3.compile(optimizer='adam', loss='mse')
print(X0.shape)
print(X0)
model3.fit(X0, y, epochs=200, verbose=0)

(13, 3)
[[0.  0.1 0.2]
 [0.1 0.2 0.3]
 [0.2 0.3 0.4]
 [0.3 0.4 0.5]
 [0.4 0.5 0.6]
 [0.5 0.6 0.7]
 [0.6 0.7 0.8]
 [0.7 0.8 0.9]
 [0.8 0.9 1. ]
 [0.9 1.  1.1]
 [1.  1.1 1.2]
 [1.1 1.2 1.3]
 [1.2 1.3 1.4]]


In [4]:
model3.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │            64 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 629 (2.46 KB)

 Trainable params: 209 (836.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 420 (1.64 KB)

In [5]:
# demonstrate prediction
x_input = array([1.3, 1.4, 1.5])
x_input = x_input.reshape((1, n_steps))
yhat = model3.predict(x_input, verbose=0)
print(yhat)

[[1.0398499]]


#### RNN

In [6]:
#print(X)

In [7]:
from keras.layers import SimpleRNN
inputs = keras.Input(shape=(n_steps, n_features))
x = SimpleRNN(64) (inputs)
output = layers.Dense(1) (x)
model21 = keras.Model(inputs = inputs, outputs=output)

model21.compile(optimizer='adam', loss='mse')
model21.fit(X, y, epochs=200, verbose=0)
model21.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)      │ (None, 3, 1)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ (None, 64)             │         4,224 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 12,869 (50.27 KB)

 Trainable params: 4,289 (16.75 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 8,580 (33.52 KB)

In [8]:
# demonstrate prediction
x_input = array([1.3, 1.4, 1.5])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model21.predict(x_input, verbose=0)
print(yhat)

[[1.5233343]]


In [9]:
from keras.layers import SimpleRNN
inputs = keras.Input(shape=(n_steps, n_features))
# intermediate layer must return a full sequence of outputs
x = SimpleRNN(64, return_sequences=True) (inputs)
x = SimpleRNN(64, return_sequences=False) (x)
x = layers.Dense(8, activation='relu') (x)
output = layers.Dense(1) (x)
model2 = keras.Model(inputs = inputs, outputs=output)

model2.compile(optimizer='adam', loss='mse')
model2.fit(X, y, epochs=200, verbose=0) # fit model

In [10]:
model2.summary()

Model: "functional_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_2 (InputLayer)      │ (None, 3, 1)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_1 (SimpleRNN)        │ (None, 3, 64)          │         4,224 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_2 (SimpleRNN)        │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 8)              │           520 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 39,029 (152.46 KB)

 Trainable params: 13,009 (50.82 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 26,020 (101.64 KB)

In [11]:
# demonstrate prediction
x_input = array([1.3, 1.4, 1.5])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model2.predict(x_input, verbose=0)
print(yhat)

[[1.5336987]]


#### LSTM

In [12]:
from keras.layers import LSTM
# define model

inputs = keras.Input(shape=(n_steps, n_features))
x = LSTM(50) (inputs)
output = layers.Dense(1) (x)
model = keras.Model(inputs = inputs, outputs=output)

model.compile(optimizer='adam', loss='mse')
model.fit(X, y, epochs=200, verbose=0)

model.summary()

Model: "functional_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_3 (InputLayer)      │ (None, 3, 1)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 50)             │        10,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 1)              │            51 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 31,355 (122.48 KB)

 Trainable params: 10,451 (40.82 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 20,904 (81.66 KB)

In [13]:
# demonstrate prediction
# x_input = array([0.7, 0.8, 0.9])
x_input = array([1.3, 1.4, 1.5])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[1.6098943]]


In [14]:
# demonstrate prediction
x_input = array([1.4, 1.5, 1.6])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[1.7134438]]


#### GRU

In [15]:
from keras.layers import GRU

inputs = keras.Input(shape=(n_steps, n_features))
x = GRU(50) (inputs)
output = layers.Dense(1) (x)
modelG = keras.Model(inputs = inputs, outputs=output)

modelG.compile(optimizer='adam', loss='mse')
modelG.fit(X, y, epochs=200, verbose=0)

modelG.summary()

Model: "functional_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_4 (InputLayer)      │ (None, 3, 1)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru (GRU)                       │ (None, 50)             │         7,950 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │            51 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 24,005 (93.77 KB)

 Trainable params: 8,001 (31.25 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 16,004 (62.52 KB)

In [16]:
# demonstrate prediction
x_input = array([1.3, 1.4, 1.5])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = modelG.predict(x_input, verbose=0)
print(yhat)

[[1.6092559]]


In [17]:
# demonstrate prediction
x_input = array([1.4, 1.5, 1.6])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = modelG.predict(x_input, verbose=0)
print(yhat)

[[1.7151194]]
