# XOR Classification Problem - linearly not separable


1.   One Perceptron - proved to be not working
2.   2 hidden neurons
3. 16 hidden neurons



---


## (Solution 0) Testing with one neuron (perceptron) - cannot be solved. Proven by Dr. Papert

In [1]:
from keras.models import Sequential
from keras.layers import Dense
from keras import optimizers
import numpy as np

X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

X1= np.array([[0.1,0],[0.1,1],[1,0.1],[0.9,1]])

model = Sequential([
    Dense(1, input_dim=2, activation='sigmoid') # 'tanh'
])
sgd = optimizers.SGD(learning_rate=0.1)
model.compile(loss='mean_squared_error', # https://keras.io/losses/
              optimizer=sgd)             # https://keras.io/optimizers/

model.fit(X, y, batch_size=1, epochs=1000, verbose=0)
# batch size: Number of samples per gradient update.
# An epoch is an iteration over the entire X and y data provided
# total number of gradient updates: 4/1 * 100 = 400

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [2]:
print(model.predict(X).round()) # does not work...
print(model.predict(X1).round()) # does not work...

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
[[1.]
 [0.]
 [0.]
 [0.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
[[1.]
 [0.]
 [0.]
 [0.]]


---
##(Solution 1) Simplest model using 2 hidden neurons and SGD optimizer, tanh activation function
<image src=https://www.robofest.net/DL/XOR1.jpg width=300>

In [3]:
from keras.models import Sequential
from keras.layers import Dense
from keras import optimizers
import numpy as np

X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

model = Sequential([
    Dense(2, input_dim=2, activation='tanh'),
    Dense(1, activation='tanh')
])

model.compile(
    loss='mean_squared_error',
    optimizer=optimizers.SGD(learning_rate=0.1), # stochastic gradient decent
    #optimizer=optimizers.RMSprop(learning_rate=0.01),
    metrics=['binary_accuracy']
)
model.fit(X, y, batch_size=1, epochs=2000, verbose=0)

In [4]:
print(model.predict(X))
print(model.predict(X).round())

X1 = np.array([[0,0.1],[0,1],[0.9,0],[1,1]]) # new test data
print(model.predict(X1).round())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step
[[ 4.6074390e-05]
 [ 9.8618883e-01]
 [ 9.8633140e-01]
 [-2.1610819e-03]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
[[ 0.]
 [ 1.]
 [ 1.]
 [-0.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
[[ 0.]
 [ 1.]
 [ 1.]
 [-0.]]


In [5]:
for layer in model.layers:
    print(layer.get_weights())

[array([[2.244663 , 1.3047345],
       [2.129538 , 1.2777212]], dtype=float32), array([-0.7069479, -1.9331042], dtype=float32)]
[array([[ 2.267465 ],
       [-2.3833585]], dtype=float32), array([-0.90521485], dtype=float32)]


---
##(Solution 1a) Simplest model using 2 hidden neurons and SGD optimizer, sigmoid activation function
<image src=https://www.robofest.net/DL/XOR_sigmoid.png width=300>

In [37]:
# using sigmoid function
from keras.models import Sequential
from keras.layers import Dense
from keras import optimizers
import numpy as np

X = np.array([[0,0],[0.1,0.1],[0,1],[0.1,0.9],[1,0],[0.9,0.1],[0.9, 0.9],[1,1]])
y = np.array([[0],  [0],      [1],  [1],      [1],  [1],      [0],       [0]])

model = Sequential([
    Dense(2, input_dim=2, activation='sigmoid'),
    Dense(1, activation='sigmoid')
])

model.compile(
    loss='mean_squared_error',
    optimizer=optimizers.SGD(learning_rate=0.1), # stochastic gradient decent
    #optimizer=optimizers.RMSprop(learning_rate=0.01),
    metrics=['binary_accuracy']
)
model.fit(X, y, batch_size=1, epochs=2000, verbose=0)

In [38]:
print(model.predict(X))
print(model.predict(X).round())

X1 = np.array([[0,0.1],[0,1],[0.9,0],[1,1]]) # new test data
print(model.predict(X1).round())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step
[[0.04395084]
 [0.08369048]
 [0.93818915]
 [0.93819153]
 [0.9382124 ]
 [0.9382101 ]
 [0.08527686]
 [0.03938338]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
[[0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step
[[0.]
 [1.]
 [1.]
 [0.]]


---
## (Solution 2) with 16 hidden neurons and adam optimizer
<image src=https://www.robofest.net/DL/XOR16.JPG width=300>

In [2]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras import optimizers

# the four different states of the XOR gate
X = np.array([[0,0],[0,1],[1,0],[1,1]], "float32") #training data

# the four expected results in the same order
y = np.array([[0],[1],[1],[0]], "float32") # target labels

m2 = Sequential([
    Dense(16, input_dim=2, activation='relu'), # relu worked
    #Dense(16, input_dim=2, activation='sigmoid'), #tanh or sigmod seems not working
    Dense(1, activation='sigmoid')
])

m2.compile(
    loss='mean_squared_error',
    optimizer=optimizers.Adam(),
    metrics=['binary_accuracy'] # metrics is to monitor and display.
    # https://machinelearningmastery.com/custom-metrics-deep-learning-keras-python/
)
m2.fit(X, y, batch_size=1, epochs=2000, verbose=0)

In [3]:
print (m2.predict(X))
print (m2.predict(X).round())

test_data = np.array([[0,0.01],[0,0.9],[1,0],[1,1]], "float32")
print (m2.predict(test_data).round())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 185ms/step
[[0.04507835]
 [0.9712327 ]
 [0.98021734]
 [0.01956292]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
[[0.]
 [1.]
 [1.]
 [0.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
[[0.]
 [1.]
 [1.]
 [0.]]


In [4]:
first_layer_weights = m2.layers[0].get_weights()[0]
first_layer_biases  = m2.layers[0].get_weights()[1]
second_layer_weights = m2.layers[1].get_weights()[0]
second_layer_biases  = m2.layers[1].get_weights()[1]

print(first_layer_weights)
print(first_layer_biases)
print(second_layer_weights)
print(second_layer_biases)

[[ 1.4902439   0.22279334 -0.34142506  0.74864507 -0.1455032   0.893708
   0.09630625  0.54124373 -0.27062702 -1.7564423   0.57361573 -0.14413509
   1.6530879   0.69456863  0.10737709 -0.35469243]
 [-1.4896351   1.4471089  -0.37359425  0.6509193  -0.08900654 -1.3294414
  -0.23488125  0.5409666  -0.09206611  1.756223    0.5736065  -0.10623646
  -1.6529261   0.69465846 -0.11089887 -0.0491969 ]]
[ 1.1269903e-04 -1.8302395e-04  0.0000000e+00 -6.5071785e-01
  0.0000000e+00  1.3764153e+00 -1.0523389e-01 -5.4133493e-01
  0.0000000e+00 -3.7106269e-04 -5.7366508e-01  0.0000000e+00
 -1.5505489e-04 -6.9474661e-01  4.7099787e-01  0.0000000e+00]
[[ 2.5242188 ]
 [ 1.074922  ]
 [ 0.2825753 ]
 [-1.0130321 ]
 [ 0.22572678]
 [-1.7589946 ]
 [-0.29793623]
 [-1.845025  ]
 [-0.50297564]
 [ 1.4980781 ]
 [-1.52565   ]
 [ 0.3268097 ]
 [ 2.8275297 ]
 [-1.143201  ]
 [-0.44029832]
 [-0.58591795]]
[-0.4250249]


## Solution 3: 2 hidden layers

In [31]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras import optimizers

# the four different states of the XOR gate
X = np.array([[0,0],[0,1],[1,0],[1,1]], "float32") #training data

# the four expected results in the same order
y = np.array([[0],[1],[1],[0]], "float32") # target labels

m2 = Sequential([
    Dense(12, input_dim=2, activation='relu'),
    Dense(4, activation='relu'),
    Dense(1, activation='sigmoid')
])

m2.compile(
    loss='mean_squared_error',
    optimizer=optimizers.SGD(learning_rate=0.01),
    metrics=['binary_accuracy'] # metrics is to monitor and display.
    # https://machinelearningmastery.com/custom-metrics-deep-learning-keras-python/
)
m2.fit(X, y, batch_size=1, epochs=2000, verbose=0)

In [32]:
print (m2.predict(X).round())

test_data = np.array([[0,0.01],[0,0.9],[1,0],[1,1]], "float32")
print (m2.predict(test_data).round())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 213ms/step
[[0.]
 [1.]
 [1.]
 [0.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
[[0.]
 [1.]
 [1.]
 [0.]]


In [33]:
print(m2.layers[0].get_weights()[0]) # 1st layer w
print(m2.layers[0].get_weights()[1]) # 1st layer bias
print(m2.layers[1].get_weights()[0]) # 2nd layer w
print(m2.layers[1].get_weights()[1]) # 2nd layer b
print(m2.layers[2].get_weights()[0]) # 3rd layer w
print(m2.layers[2].get_weights()[1]) # 3rd layer b

[[ 0.77463037 -0.3640998   0.0664744   0.9325898  -1.1418909  -0.5089944
  -0.5428223   0.74599373  0.44050452 -0.29540345 -0.6065067  -0.6192178 ]
 [-0.774505   -0.5818594   0.20631069 -0.9325172   1.1421189   0.0509554
  -0.22579029 -0.7458374   0.34493056 -0.07796401 -0.5689869   0.6193573 ]]
[-1.5085250e-05  0.0000000e+00 -2.7449125e-05 -4.1886495e-05
 -4.5034874e-05  3.3576684e-06  0.0000000e+00 -2.1431646e-05
  5.5385578e-01  0.0000000e+00  0.0000000e+00 -5.0573442e-05]
[[-0.6872018   0.22927365  0.447633    0.3374563 ]
 [-0.0228036   0.13724953  0.17577171 -0.21634394]
 [-0.32715183 -0.48720285  0.45747718  0.32737115]
 [-0.7212219   0.11680149  0.8839414   0.3101034 ]
 [-1.1672366  -0.49678627  1.0446491   0.20480065]
 [ 0.04423636 -0.22202718  0.31909382 -0.4656825 ]
 [-0.02841181  0.46574646  0.09049636  0.03466237]
 [-0.597024    0.3303297   0.64435744  0.49386555]
 [ 0.8714805  -0.31999782  0.30374417  0.02366432]
 [-0.27047294 -0.2778232   0.52601844 -0.46648917]
 [ 0.2561

In [34]:
for layer in m2.layers:
    print(layer.get_weights())

[array([[ 0.77463037, -0.3640998 ,  0.0664744 ,  0.9325898 , -1.1418909 ,
        -0.5089944 , -0.5428223 ,  0.74599373,  0.44050452, -0.29540345,
        -0.6065067 , -0.6192178 ],
       [-0.774505  , -0.5818594 ,  0.20631069, -0.9325172 ,  1.1421189 ,
         0.0509554 , -0.22579029, -0.7458374 ,  0.34493056, -0.07796401,
        -0.5689869 ,  0.6193573 ]], dtype=float32), array([-1.5085250e-05,  0.0000000e+00, -2.7449125e-05, -4.1886495e-05,
       -4.5034874e-05,  3.3576684e-06,  0.0000000e+00, -2.1431646e-05,
        5.5385578e-01,  0.0000000e+00,  0.0000000e+00, -5.0573442e-05],
      dtype=float32)]
[array([[-0.6872018 ,  0.22927365,  0.447633  ,  0.3374563 ],
       [-0.0228036 ,  0.13724953,  0.17577171, -0.21634394],
       [-0.32715183, -0.48720285,  0.45747718,  0.32737115],
       [-0.7212219 ,  0.11680149,  0.8839414 ,  0.3101034 ],
       [-1.1672366 , -0.49678627,  1.0446491 ,  0.20480065],
       [ 0.04423636, -0.22202718,  0.31909382, -0.4656825 ],
       [-0.028411

In [35]:
w_wrong_way = np.array([-1.5762874, -1.0371548, -0.00142884, 1.5773863,  1.1721394, 1.0371915,
              -2.000427  ,  0.27228707,  -0.00033456,  1.4251844 , -0.08215237, -0.25072166,
               -2.580953, -0.7357822, 1.5679584
            ])

w = np.array([-1.5762874, 1.5773863, -0.00142884,  -1.0371548, 1.1721394, 1.0371915,
              -2.000427, 1.4251844, -0.00033456, 0.27228707, -0.08215237, -0.25072166,
               -2.580953, -0.7357822, 1.5679584
            ]) # this is correct