## XOR with 3 classes

<pre>
   | x0 | x1 |XOR3|
   |----|----|----|
   |0.0 |0.0 | 0  |
   |0.0 |1.0 | 1  |
   |1.0 |0.0 | 1  |
   |1.0 |1.0 | 0  |
   |0.5 |0.5 | 2  |
</pre>

In [ ]:
import numpy as np
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense

# the five different states of the XOR3 gate
X = np.array([[0,0],[0,1],[1,0],[1,1],[0.5,0.5]])

# the five expected results in the same order
y = np.array([[0],[1],[1],[0],[2]])

Xt = np.array([[0,0.1],[0.1,1],[0.9,0],[0.9,1],[0.55,0.45]])
yt = np.array([[0],[1],[1],[0],[2]])

In [ ]:
# Using 'sparse_categorical_crossentropy'

model = Sequential([
    keras.Input(shape=(2,)),
    Dense(16, activation='relu'),
    Dense(3, activation='softmax')
])

model.compile(
  optimizer='rmsprop',
  loss='sparse_categorical_crossentropy', # target labels are integers
  metrics=['accuracy']
)
model.fit(X, y, batch_size=1, epochs=1300, verbose=0)

In [ ]:
print (model.predict(X))
print (model.predict(X, verbose=0).round())
(loss, acc) = model.evaluate(Xt, yt)
print (f"loss = {loss}, acc = {acc}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
[[9.7201216e-01 2.8205274e-03 2.5167249e-02]
 [6.9571484e-05 9.9944180e-01 4.8856233e-04]
 [2.9585676e-04 9.9964142e-01 6.2687453e-05]
 [9.9027681e-01 1.9060351e-05 9.7042220e-03]
 [3.9643530e-02 8.0707384e-04 9.5954937e-01]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 175ms/step - accuracy: 1.0000 - loss: 0.0373
loss = 0.03734573721885681, acc = 1.0


In [1]:
# model save into a file and reloading the model
model.summary()
model.save('xor3.keras') # the file is stored on the cloud account. Will stay a day

model.load_weights('xor3.keras')
print (model.predict(X))
print (model.predict(X, verbose=0).round())
model.evaluate(Xt, yt)

m2 = keras.models.load_model('xor3.keras')
m2.summary()
print (m2.predict(X))
print (m2.predict(X, verbose=0).round())
(loss, acc) = m2.evaluate(Xt, yt)
print (f"loss = {loss}, acc = {acc}")

NameError: name 'model' is not defined

In [ ]:
# Using 'categorical_crossentropy'

model = Sequential([
    keras.Input(shape=(2,)),
    Dense(16, activation='relu'),
    Dense(3, activation='softmax')
])
model.compile(
  optimizer='rmsprop',
  loss='categorical_crossentropy', # target labels are 1hot encoded format
  metrics=['accuracy']
)

# Converting y to one-hot encoded format with shape (5,3)
y_1hot = keras.utils.to_categorical(y, num_classes=3)
model.fit(X, y_1hot, batch_size=1, epochs=1300, verbose=0)
print (model.predict(X))
print (model.predict(X, verbose=0).round())
yt_1hot = keras.utils.to_categorical(yt, num_classes=3)
model.evaluate(Xt, yt_1hot)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
[[9.2823094e-01 2.6390199e-03 6.9130085e-02]
 [7.1440230e-04 9.9920589e-01 7.9665529e-05]
 [1.5152052e-04 9.9980527e-01 4.3238895e-05]
 [8.7318039e-01 3.9858445e-05 1.2677975e-01]
 [2.7102765e-01 3.8986828e-04 7.2858250e-01]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 183ms/step - accuracy: 1.0000 - loss: 0.1411


[0.14108029007911682, 1.0]